# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Temperature(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, timestamp: datetime=None, value: float=None):  # noqa: E501
        """Temperature - a model defined in Swagger

        :param name: The name of this Temperature.  # noqa: E501
        :type name: str
        :param timestamp: The timestamp of this Temperature.  # noqa: E501
        :type timestamp: datetime
        :param value: The value of this Temperature.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'name': str,
            'timestamp': datetime,
            'value': float
        }

        self.attribute_map = {
            'name': 'name',
            'timestamp': 'timestamp',
            'value': 'value'
        }
        self._name = name
        self._timestamp = timestamp
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Temperature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Temperature of this Temperature.  # noqa: E501
        :rtype: Temperature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Temperature.


        :return: The name of this Temperature.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Temperature.


        :param name: The name of this Temperature.
        :type name: str
        """

        self._name = name

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this Temperature.


        :return: The timestamp of this Temperature.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this Temperature.


        :param timestamp: The timestamp of this Temperature.
        :type timestamp: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def value(self) -> float:
        """Gets the value of this Temperature.


        :return: The value of this Temperature.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this Temperature.


        :param value: The value of this Temperature.
        :type value: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
