openapi: 3.0.1
info:
  title: Sample OpenAPI Specification
  description: An OpenAPI specification example
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: http://localhost:8080/
  description: Example API Service
paths:
  /Temperatures:
    get:
      description: Gets a Temperature
      operationId: get_temperature
      responses:
        "200":
          description: Temperature found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temperature'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
      x-openapi-router-controller: swagger_server.controllers.default_controller
    post:
      description: Creates a new Temperature
      operationId: create_temperature
      requestBody:
        description: The Temperature to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Temperature'
      responses:
        "200":
          description: Temperature added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temperature'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Temperature:
      required:
      - display_name
      - email
      type: object
      properties:
        name:
          type: string
          readOnly: true
        display_name:
          maxLength: 20
          minLength: 1
          type: string
        email:
          type: string
          format: email
      example:
        name: name
        display_name: display_name
        email: ""
    ErrorMessage:
      required:
      - error_code
      - error_message
      type: object
      properties:
        error_code:
          type: string
        error_message:
          type: string
  parameters:
    Temperature_id:
      name: Temperature_id
      in: path
      description: ID of Temperature
      required: true
      style: simple
      explode: false
      schema:
        type: string
    photo_id:
      name: photo_id
      in: path
      description: ID of photo
      required: true
      style: simple
      explode: false
      schema:
        type: string
    photo_ids:
      name: photo_ids
      in: query
      description: a collection of photo IDs
      required: true
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string

