openapi: 3.0.1
info:
  title: Sample OpenAPI Specification
  description: An OpenAPI specification example
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: http://localhost:8080/my-temp-service/0.0.1
  description: Example API Service
paths:
  /Temperatures:
    get:
      description: Gets a Temperature
      operationId: get_temperature
      parameters:
      - name: date
        in: query
        description: date of Temperature
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date
      responses:
        "200":
          description: Temperature found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temperature'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      description: Creates a new Temperature
      operationId: create_temperature
      requestBody:
        description: The Temperature to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Temperature'
      responses:
        "200":
          description: Temperature added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temperature'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Temperature:
      required:
      - value
      type: object
      properties:
        date:
          type: string
          format: date
          readOnly: true
        value:
          type: number
          format: double
      example:
        date: 2020-07-08 15:00:44.254187
        value: 20.7
    ErrorMessage:
      required:
      - error_code
      - error_message
      type: object
      properties:
        error_code:
          type: string
        error_message:
          type: string

