openapi: 3.0.1
info:
  title: Sample OpenAPI Specification
  description: An OpenAPI specification example
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: http://localhost:8080/
  description: Example API Service
paths:
  /Temperatures:
    get:
      description: Gets a Temperature
      operationId: get_temperature
      responses:
        "200":
          description: Temperature found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temperature'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
      x-openapi-router-controller: swagger_server.controllers.default_controller
    post:
      description: Creates a new Temperature
      operationId: create_temperature
      requestBody:
        description: The Temperature to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Temperature'
      responses:
        "200":
          description: Temperature added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Temperature'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Temperature:
      required:
      - timestamp
      - value
      type: object
      properties:
        name:
          type: string
          readOnly: true
        timestamp:
          type: string
          format: date-time
        value:
          type: number
          format: double
      example:
        name: name
        value: 0.80082819046101150206595775671303272247314453125
        timestamp: 2000-01-23T04:56:07.000+00:00
    ErrorMessage:
      required:
      - error_code
      - error_message
      type: object
      properties:
        error_code:
          type: string
        error_message:
          type: string

