apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service:  fair-cell-service
  name:  fair-cell-service
spec:
  selector:
    matchLabels:
      io.kompose.service:  fair-cell-service
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service:  fair-cell-service
    spec:
      containers:
      - image: cloudcells/classifiers
        name:  fair-cell-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: "30m"
          requests:
            cpu: "30m"
      restartPolicy: Always
status: {}
