apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fair-cell-service
  name: fair-cell-service
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    name: http
  selector:
    io.kompose.service: fair-cell-service
status:
  loadBalancer: {} 
