apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: my-temp-service
  name: my-temp-service
spec:
  type: NodePort  
  ports:
  - port: 8082
    protocol: TCP
    name: http
  selector:
    io.kompose.service: my-temp-service
status:
  loadBalancer: {} 
