apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service:  my-temp-service
  name:  my-temp-service
spec:
  selector:
    matchLabels:
      io.kompose.service:  my-temp-service
  replicas: 1
  strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 50%
            maxUnavailable: 50%
  minReadySeconds: 10
  revisionHistoryLimit: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service:  my-temp-service
    spec:
      containers:
      - env:
        - name: MONGO_HOST
          value: mongo  
        image: qcdis/my-temp-service
        name:  my-temp-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
status: {}
