- hosts: all
  become: yes
  gather_facts: no
  vars:
    git_repo: https://github.com/skoulouzis/DevOpsTutorial.git

  tasks:
    - name: Update
      apt:
        update_cache: yes
      register: update_result
      ignore_errors: True

    - name: Update from shell
      shell: apt update
      when: update_result.failed == True


    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

    - name: Install Python
      raw: apt install -y python-minimal
      when: check_python.rc != 0

    - name: Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
          - mongodb
          - python3
          - python3-pip
          - screen

    - name: Make sure a mongo is running
      systemd:
        state: started
        name: mongodb

    - name: clone repo
      git:
        repo: "{{ git_repo }}"
        dest: /DevOpsTutorial
        version: summer_school

    - name: pip install setuptools
      pip:
        name: setuptools
        executable: pip3

    - name: pip install requirements
      pip:
        requirements: /DevOpsTutorial/api_server/requirements.txt
        executable: pip3

    - name: Make start exec
      file: dest=/DevOpsTutorial/api_server/start.sh mode=+x
    -
    - name: Start
      shell: cd /DevOpsTutorial/api_server && ./start.sh